# Copyright 2025 Abion AB
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.{{ .Values.groupName }}
  labels:
    app: {{ include "cert-manager-webhook-abion.name" . }}
    chart: {{ include "cert-manager-webhook-abion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "cert-manager-webhook-abion.servingCertificate" . }}"
  {{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  group: {{ .Values.groupName }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "cert-manager-webhook-abion.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1alpha1
